# Numérotation à partir de 1
set -g base-index 1
setw -g pane-base-index 1

# Recharger la config
bind r source-file ~/.tmux.conf \; display "Config rechargée !"

# Navigation entre panneaux avec Alt+flèches
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# Souris
set -g mouse on

# Historique
set -g history-limit 10000

# Couleurs
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# ─── Plugins ───────────────────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'   # bonnes pratiques par défaut
set -g @plugin 'tmux-plugins/tmux-resurrect'  # sauvegarde les sessions
set -g @plugin 'tmux-plugins/tmux-continuum'  # sauvegarde automatique
set -g @plugin 'catppuccin/tmux'              # thème

# ─── Config Catppuccin ─────────────────────────────────────
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_status_style "rounded"

# ─── Config Resurrect / Continuum ──────────────────────────
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# Initialiser TPM (toujours en dernière ligne)
run '~/.tmux/plugins/tpm/tpm'
